db_data_food_items = [
    { "type":1, "name":"English muffins, whole wheat", "source":"Safeway", "unit":"1 bag of 6", "unit_portions":3.00, "unit_price":2.50 },
    { "type":1, "name":"Mission Whole Wheat Tortilla (2 per portion)", "source":"Safeway", "unit":"1 bag, 10 tortillas", "unit_portions":5.00, "unit_price":3.30 },
    { "type":1, "name":"Signature Select Brown Rice", "source":"Safeway", "unit":"1 bag (5 cups)", "unit_portions":15.00, "unit_price":5.30 },
    { "type":1, "name":"Whole Wheat Bread", "source":"Costco", "unit":"48 slices (2 loaf package)", "unit_portions":24.00, "unit_price":7.00 },
    { "type":1, "name":"Lindberg Organic Short-Grain Brown Rice", "source":"Costco", "unit":"1 bag (30 cups, dry)", "unit_portions":105.00, "unit_price":13.80 },
    { "type":2, "name":"Cottage cheese, 1%", "source":"Safeway", "unit":"16oz container", "unit_portions":2.00, "unit_price":2.00 },
    { "type":2, "name":"Shredded Mozzarella (8oz)", "source":"Safeway", "unit":"1x 8oz bag", "unit_portions":5.33, "unit_price":3.50 },
    { "type":2, "name":"Lucerne Skim Milk", "source":"Safeway", "unit":"1 Gallon", "unit_portions":19.00, "unit_price":4.00 },
    { "type":2, "name":"O Organics (Ultra Pasteurized, half gallon)", "source":"Safeway", "unit":"0.5 Gallons", "unit_portions":9.50, "unit_price":4.00 },
    { "type":2, "name":"Costco Skim Milk", "source":"Costco", "unit":"2x 1 gallon jugs", "unit_portions":38.00, "unit_price":5.60 },
    { "type":2, "name":"O Organics (Gallon)", "source":"Safeway", "unit":"1 Gallon", "unit_portions":19.00, "unit_price":6.00 },
    { "type":2, "name":"Shredded Mozzarella (32oz)", "source":"Safeway", "unit":"1x 32oz bag", "unit_portions":21.33, "unit_price":7.00 },
    { "type":3, "name":"Canned Olives (6oz)", "source":"Safeway", "unit":"1 can", "unit_portions":1.50, "unit_price":1.50 },
    { "type":3, "name":"Avocado", "source":"Safeway", "unit":"1 avocado", "unit_portions":2.00, "unit_price":3.00 },
    { "type":3, "name":"Musco Pearls (6oz cans)", "source":"Costco", "unit":"1 package of 8 cans", "unit_portions":12.00, "unit_price":11.00 },
    { "type":3, "name":"Kirkland Signature Extra Virgin Olive Oil", "source":"Costco", "unit":"1x 2L container", "unit_portions":135.00, "unit_price":15.00 },
    { "type":4, "name":"Costco Bananas", "source":"Costco", "unit":"1 lb", "unit_portions":3.20, "unit_price":0.63 },
    { "type":4, "name":"Bananas", "source":"Safeway", "unit":"1 lb", "unit_portions":3.20, "unit_price":0.70 },
    { "type":4, "name":"Daybreak Mixed Fruit", "source":"Costco", "unit":"1 lb ", "unit_portions":3.20, "unit_price":2.95 },
    { "type":4, "name":"Frozen Blueberries", "source":"Costco", "unit":"3 lb bag", "unit_portions":9.60, "unit_price":8.60 },
    { "type":4, "name":"O Organics Frozen Blueberries", "source":"Safeway", "unit":"3 lb bag", "unit_portions":9.60, "unit_price":14.00 },
    { "type":4, "name":"KS Three Berry Blend Frozen", "source":"Costco", "unit":"4 lb bag", "unit_portions":12.80, "unit_price":15.00 },
    { "type":5, "name":"Lucerne Egg Carton", "source":"Safeway", "unit":"12 eggs", "unit_portions":2.00, "unit_price":2.40 },
    { "type":5, "name":"Costco Eggs", "source":"Costco", "unit":"1 dozen", "unit_portions":2.00, "unit_price":2.50 },
    { "type":5, "name":"House Foods Tofu", "source":"Safeway", "unit":"1x 19oz container", "unit_portions":6.33, "unit_price":2.70 },
    { "type":5, "name":"Foster Farms Chicken Breast (Shrinks by ~half when cooked)", "source":"Costco", "unit":"1 lb", "unit_portions":5.33, "unit_price":2.90 },
    { "type":5, "name":"Pork Tenderloin", "source":"Safeway", "unit":"1 lb", "unit_portions":5.33, "unit_price":3.00 },
    { "type":5, "name":"Lucerne Egg Carton (1.5 dozen)", "source":"Safeway", "unit":"18 eggs", "unit_portions":3.00, "unit_price":3.50 },
    { "type":5, "name":"Pork Tenderloin", "source":"Costco", "unit":"1 lb", "unit_portions":5.33, "unit_price":3.90 },
    { "type":5, "name":"Jennie-O Turkey Bacon (30 cal / slice)", "source":"Safeway", "unit":"1 package, 22 slices", "unit_portions":7.33, "unit_price":4.00 },
    { "type":5, "name":"Ground beef, 88% lean", "source":"Costco", "unit":"1 lb ", "unit_portions":5.33, "unit_price":4.80 },
    { "type":5, "name":"Ground beef, 93% lean (3-lb pack)", "source":"Safeway", "unit":"1 lb", "unit_portions":5.33, "unit_price":5.00 },
    { "type":5, "name":"Lucerne Liquid Egg Whites (32 oz)", "source":"Safeway", "unit":"1 carton", "unit_portions":4.50, "unit_price":5.50 },
    { "type":5, "name":"Rockfish", "source":"Costco", "unit":"1 lb ", "unit_portions":5.33, "unit_price":6.00 },
    { "type":5, "name":"Ham (Uncured, No Nitrates)", "source":"Safeway", "unit":"1 lb", "unit_portions":5.33, "unit_price":6.00 },
    { "type":5, "name":"Cage-Free Egg Whites (6x16oz)", "source":"Costco", "unit":"1x 96oz box", "unit_portions":13.50, "unit_price":12.00 },
    { "type":5, "name":"Columbus Craft Meats Turkey Bacon (45 cal / slice)", "source":"Costco", "unit":"1 package, 40 slices", "unit_portions":20.00, "unit_price":15.00 },
    { "type":5, "name":"Shrimp", "source":"Costco", "unit":"2lb bag", "unit_portions":10.67, "unit_price":15.60 },
    { "type":5, "name":"Salmon Fillet", "source":"Costco", "unit":"1 lb ", "unit_portions":5.33, "unit_price":18.00 },
    { "type":5, "name":"Tilapia", "source":"Costco", "unit":"12x 4oz cuts", "unit_portions":16.00, "unit_price":18.00 },
    { "type":5, "name":"Kirkland Signature Chicken Breast", "source":"Costco", "unit":"6.5 lb bag", "unit_portions":34.67, "unit_price":26.00 },
    { "type":5, "name":"ON Whey Protein Powder 1.9 lbs", "source":"Amazon", "unit":"1 container", "unit_portions":28.00, "unit_price":35.00 },
    { "type":5, "name":"Puori Protein Powder (Health-Conscious)", "source":"Puori", "unit":"1 bag", "unit_portions":30.00, "unit_price":60.00 },
    { "type":5, "name":"ON Whey Protein Powder 5.6 lbs", "source":"Costco", "unit":"1 bag", "unit_portions":80.00, "unit_price":63.00 },
    { "type":5, "name":"ON Whey Protein Powder 4.8 lbs", "source":"Amazon", "unit":"1 container", "unit_portions":68.00, "unit_price":75.00 },
    { "type":5, "name":"ON Whey Protein Powder 10 lbs", "source":"Amazon", "unit":"1 bag", "unit_portions":149.00, "unit_price":133.00 },
    { "type":6, "name":"Cucumber", "source":"Safeway", "unit":"1 cucumber", "unit_portions":2.00, "unit_price":1.00 },
    { "type":6, "name":"Romaine Lettuce", "source":"Safeway", "unit":"1 head", "unit_portions":6.00, "unit_price":2.00 },
    { "type":6, "name":"Baby Carrots", "source":"Safeway", "unit":"1 bag", "unit_portions":4.00, "unit_price":3.00 },
    { "type":6, "name":"Asparagus", "source":"Safeway", "unit":"1 lb", "unit_portions":2.00, "unit_price":5.00 },
    { "type":6, "name":"Stir Fry Veggies", "source":"Costco", "unit":"5lb bag", "unit_portions":11.30, "unit_price":9.80 },
]